=== anjali-rgpt/PlacementPortal/XML/student_company_reg.dtd
<!ELEMENT Registrations(Student+)>
<!ELEMENT Student(FirstName,MiddleName,LastName,RollNumber,EmailID,PhoneNumber,Address,Degree,Department,GradYear,CGPA,Companies)>
<!ELEMENT FirstName(#PCDATA)>
<!ELEMENT MiddleName(#PCDATA)>
<!ELEMENT LastName(#PCDATA)>
<!ELEMENT RollNumber(#PCDATA)>
<!ELEMENT EmailID(#PCDATA)>
<!ELEMENT PhoneNumber(#PCDATA)>
<!ELEMENT Address(#CDATA)>
<!ELEMENT Degree(#PCDATA)>
<!ELEMENT Department(#PCDATA)>
<!ELEMENT GradYear(#PCDATA)>
<!ELEMENT CGPA(#PCDATA)>
<!ELEMENT Companies (Company*)>
<!ELEMENT Company(CompanyName,RoleName,Type,Question,ResumeLink,Status)>
<!ELEMENT CompanyName(#CDATA)>
<!ELEMENT RoleName(#CDATA)>
<!ELEMENT Type(#PCDATA)>
<!ELEMENT Question(#CDATA)>
<!ELEMENT ResumeLink(#CDATA)>
<!ELEMENT Status(#PCDATA)>

=== anjali-rgpt/PlacementPortal/XML/student_company_reg.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="student_company_reg.xsl"?>

<!DOCTYPE Registrations SYSTEM "student_company_reg.dtd">

<Registrations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student_company_reg.xsd">
    
    <Student>
        <FirstName>Anjali</FirstName>
        <MiddleName></MiddleName>
        <LastName>Ragupathi</LastName>
        <RollNumber>CB.EN.U4CSE17307</RollNumber>
        <EmailID>anjaliragupathi99@gmail.com</EmailID>
        <PhoneNumber>7502712000</PhoneNumber>
        <Address>9, ABC Street, KLM Nagar, Coimbatore </Address>
        <Degree>B.Tech.</Degree>
        <Department>Computer Science and Engineering</Department>
        <GradYear>2021</GradYear>
        <CGPA>9.64</CGPA>
        
        <Companies>
            
            <Company>
                <CompanyName>Amazon</CompanyName>
                <RoleName>R&amp;D</RoleName>
                <Type>Internship</Type>
                <Question>I want to join this company because it is fun and nice</Question>
                <ResumeLink>http://www.drive.google.com/resume.pdf</ResumeLink>
                <Status>Registered</Status>
                
            </Company>
            
            <Company>
                <CompanyName>Microsoft</CompanyName>
                <RoleName>R&amp;D</RoleName>
                <Type>Internship</Type>
                <Question>I want to join this company because it does quality research</Question>
                <ResumeLink>http://www.drive.google.com/resume.pdf</ResumeLink>
                <Status>Registered</Status>
                
            </Company>
            
        </Companies>
        
    </Student>
    
    <Student>
        <FirstName>Sheela</FirstName>
        <MiddleName>J</MiddleName>
        <LastName>Gupta</LastName>
        <RollNumber>CB.EN.U4CSE17545</RollNumber>
        <EmailID>sheelagupta@gmail.com</EmailID>
        <PhoneNumber>8502712090</PhoneNumber>
        <Address>8, Canterbury Villas, Mumbai </Address>
        <Degree>B.Tech.</Degree>
        <Department>Computer Science and Engineering</Department>
        <GradYear>2021</GradYear>
        <CGPA>8.5</CGPA>
        
        <Companies>
            
            <Company>
                <CompanyName>Mr.Cooper</CompanyName>
                <RoleName>Software Engineer</RoleName>
                <Type>FTE</Type>
                <Question>Mr.Cooper has been my passion for a long time. I like the work they do in financial consulting and want to make a difference.</Question>
                <ResumeLink>http://www.drive.google.com/resume.pdf</ResumeLink>
                <Status>Registered</Status>
                
            </Company>
            
            <Company>
                <CompanyName>SAP Labs</CompanyName>
                <RoleName>Software Engineer</RoleName>
                <Type>Internship</Type>
                <Question>The Lab attracts me because it is a place for opportunity.</Question>
                <ResumeLink>http://www.drive.google.com/resume.pdf</ResumeLink>
                <Status>Selected</Status>
                
            </Company>
            
        </Companies>
        
    </Student>

    <Student>
        <FirstName>Harshavardhini</FirstName>
        <MiddleName></MiddleName>
        <LastName>Saravanakumaran</LastName>
        <RollNumber>CB.EN.U4ECE17334</RollNumber>
        <EmailID>harshavardhini_s@gmail.com</EmailID>
        <PhoneNumber>9502712890</PhoneNumber>
        <Address>1, Svarga Hill Road, Vadavalli, Coimbatore, Tamil Nadu </Address>
        <Degree>B.Tech.</Degree>
        <Department>Electronics and Communication Engineering</Department>
        <GradYear>2021</GradYear>
        <CGPA>8.9</CGPA>
        <Companies></Companies>
    </Student>
    
    
</Registrations>
